In [2]:
##import pandas
import pandas as pd

In [4]:
ems2020_excerpt_df = pd.read_csv ("ems20_1st_6months_excerpt.csv")

In [6]:
ems2020_excerpt_df.head (10)

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,...,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR,source
0,201101264,2020-04-19 10:25:47,INJMIN,7,INJMIN,7,04/19/2020 10:26:24 AM,Y,37,04/19/2020 10:26:24 AM,...,40.0,8.0,201.0,7.0,15.0,N,N,N,N,chunk170.csv
1,200423766,2020-02-11 19:25:47,CARD,3,SICK,6,02/11/2020 07:25:56 PM,Y,9,02/11/2020 07:26:09 PM,...,52.0,14.0,207.0,10.0,15.0,N,N,N,N,chunk166.csv
2,200434110,2020-02-12 21:36:52,UNC,2,UNC,2,02/12/2020 09:37:24 PM,Y,32,02/12/2020 09:38:27 PM,...,106.0,32.0,410.0,27.0,8.0,N,N,N,N,chunk166.csv
3,201610121,2020-06-09 00:52:30,DRUG,4,DRUG,4,06/09/2020 12:52:44 AM,Y,14,06/09/2020 12:52:59 AM,...,19.0,4.0,108.0,2.0,12.0,N,N,N,N,chunk171.csv
4,200034112,2020-01-03 20:44:05,DRUG,4,DRUG,4,01/03/2020 08:44:11 PM,Y,6,01/03/2020 08:44:17 PM,...,66.0,39.0,312.0,15.0,7.0,N,N,N,N,chunk165.csv
5,200530247,2020-02-22 01:26:18,DRUG,4,DRUG,4,02/22/2020 01:27:21 AM,Y,63,02/22/2020 01:27:41 AM,...,25.0,8.0,111.0,4.0,12.0,N,N,N,N,chunk167.csv
6,200543279,2020-02-23 19:08:27,UNC,2,UNC,2,02/23/2020 07:08:44 PM,Y,17,02/23/2020 07:09:16 PM,...,44.0,8.0,204.0,9.0,15.0,N,N,N,N,chunk167.csv
7,201471743,2020-05-26 12:45:46,INJURY,5,INJURY,5,05/26/2020 12:46:04 PM,Y,18,05/26/2020 12:46:15 PM,...,41.0,17.0,202.0,8.0,15.0,N,N,N,N,chunk171.csv
8,201180116,2020-04-27 00:57:48,EDP,7,EDPC,7,04/27/2020 12:58:07 AM,Y,19,04/27/2020 12:58:15 AM,...,50.0,11.0,208.0,10.0,16.0,N,N,N,N,chunk170.csv
9,200572739,2020-02-26 15:15:25,CARDBR,2,CARDBR,2,02/26/2020 03:16:35 PM,Y,70,02/26/2020 03:16:49 PM,...,106.0,28.0,410.0,27.0,5.0,N,N,N,N,chunk167.csv

In [8]:
ems2020_excerpt_df.tail ()

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,...,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR,source
13112,200393407,2020-02-08 19:49:33,DIFFBR,2,DIFFBR,2,02/08/2020 07:52:34 PM,Y,181,02/08/2020 07:53:00 PM,...,72.0,38.0,307.0,15.0,7.0,N,N,N,N,chunk166.csv
13113,200034618,2020-01-03 22:51:33,INJURY,5,INJURY,5,01/03/2020 10:51:39 PM,Y,6,01/03/2020 10:52:21 PM,...,75.0,42.0,305.0,19.0,8.0,N,N,N,N,chunk165.csv
13114,200424355,2020-02-11 21:51:09,SICK,6,SICK,6,02/11/2020 09:52:09 PM,Y,60,02/11/2020 09:52:18 PM,...,48.0,15.0,206.0,10.0,15.0,N,N,N,N,chunk166.csv
13115,201742708,2020-06-22 15:57:44,MVAINJ,4,MVAINJ,4,06/22/2020 03:58:07 PM,Y,23,06/22/2020 03:58:19 PM,...,62.0,47.0,311.0,21.0,11.0,N,N,N,N,chunk172.csv
13116,200865674,2020-03-26 19:33:19,DIFFFC,2,DIFFFC,2,03/26/2020 07:33:50 PM,Y,31,03/26/2020 07:34:08 PM,...,103.0,27.0,412.0,29.0,5.0,N,N,N,N,chunk168.csv

In [10]:
ems2020_excerpt_df.sample(20)

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,...,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR,source
11053,200854427,2020-03-25 17:16:08,INJURY,5,INJURY,5,03/25/2020 05:17:13 PM,Y,65,03/25/2020 05:20:50 PM,...,32.0,9.0,110.0,5.0,13.0,N,N,N,N,chunk168.csv
6141,201102457,2020-04-19 16:14:18,SICK,6,SICK,6,04/19/2020 04:14:49 PM,Y,31,04/19/2020 04:15:25 PM,...,49.0,13.0,211.0,11.0,14.0,N,N,N,N,chunk170.csv
7154,200952681,2020-04-04 12:35:23,BURNMA,3,BURNMA,3,04/04/2020 12:35:31 PM,Y,8,04/04/2020 12:36:02 PM,...,43.0,17.0,209.0,8.0,15.0,N,N,N,N,chunk169.csv
2301,200312075,2020-01-31 12:52:45,CHOKE,1,CHOKE,1,01/31/2020 12:53:02 PM,Y,17,01/31/2020 12:53:15 PM,...,13.0,2.0,105.0,2.0,12.0,N,N,N,N,chunk166.csv
9048,200312692,2020-01-31 14:56:51,EDP,7,EDP,7,01/31/2020 02:59:01 PM,Y,130,01/31/2020 02:59:34 PM,...,46.0,15.0,205.0,10.0,15.0,N,N,N,N,chunk166.csv
5352,201260581,2020-05-05 06:31:52,INJURY,5,INJURY,5,05/05/2020 06:32:13 AM,Y,21,05/05/2020 06:32:32 AM,...,60.0,47.0,313.0,21.0,11.0,N,N,N,N,chunk170.csv
2041,200603218,2020-02-29 18:49:34,UNC,2,UNC,2,02/29/2020 06:49:50 PM,Y,16,02/29/2020 06:50:03 PM,...,109.0,20.0,407.0,25.0,6.0,N,N,N,N,chunk167.csv
8147,200935825,2020-04-02 21:17:39,DIFFBR,2,DIFFBR,2,04/02/2020 09:19:19 PM,Y,100,04/02/2020 09:20:32 PM,...,42.0,17.0,203.0,12.0,15.0,N,N,N,N,chunk169.csv
11813,200342033,2020-02-03 11:49:04,SICK,6,SICK,6,02/03/2020 11:49:13 AM,Y,9,02/03/2020 11:49:27 AM,...,19.0,4.0,108.0,2.0,12.0,N,N,N,N,chunk166.csv
628,201561513,2020-06-04 11:31:26,SICK,6,SICK,6,06/04/2020 11:36:14 AM,Y,288,06/04/2020 11:36:25 AM,...,44.0,8.0,204.0,9.0,15.0,Y,N,N,N,chunk171.csv
35,200623062,2020-03-02 16:39:23,SICK,6,SICK,6,03/02/2020 04:39:54 PM,Y,31,03/02/2020 04:39:59 PM,...,121.0,51.0,502.0,31.0,11.0,N,N,N,N,chunk167.csv
11395,200273986,2020-01-27 19:27:19,DRUG,4,DRUG,4,01/27/2020 07:27:32 PM,Y,13,01/27/2020 07:27:46 PM,...,46.0,15.0,205.0,10.0,15.0,N,N,N,N,chunk166.csv
10013,200161319,2020-01-16 09:43:50,EDPC,7,EDPC,7,01/16/2020 09:44:50 AM,Y,60,01/16/2020 09:45:16 AM,...,44.0,16.0,204.0,9.0,15.0,N,N,N,N,chunk165.csv
2369,200343611,2020-02-03 17:16:15,SICK,6,SICK,6,02/03/2020 05:16:24 PM,Y,9,02/03/2020 05:16:36 PM,...,105.0,23.0,413.0,26.0,3.0,N,N,N,N,chunk166.csv
6170,200091726,2020-01-09 11:36:07,CARDBR,2,CARDBR,2,01/09/2020 11:36:14 AM,Y,7,01/09/2020 11:36:31 AM,...,49.0,13.0,211.0,11.0,14.0,N,N,N,N,chunk165.csv
7557,201233622,2020-05-02 21:49:11,SICK,6,CARD,3,05/02/2020 10:33:06 PM,Y,2635,05/02/2020 10:33:39 PM,...,52.0,11.0,207.0,10.0,13.0,Y,N,N,N,chunk170.csv
2099,201763860,2020-06-24 22:09:59,UNKNOW,4,UNKNOW,4,06/24/2020 10:10:11 PM,Y,12,06/24/2020 10:11:16 PM,...,60.0,47.0,313.0,21.0,11.0,N,N,N,N,chunk172.csv
1232,200480339,2020-02-17 02:08:30,INJMAJ,3,INJMAJ,3,02/17/2020 02:08:36 AM,Y,6,02/17/2020 02:08:59 AM,...,23.0,9.0,111.0,4.0,13.0,N,N,N,N,chunk167.csv
12994,201712619,2020-06-19 16:51:05,OTHER,6,OTHER,6,06/19/2020 04:51:43 PM,Y,38,06/19/2020 04:52:29 PM,...,111.0,23.0,411.0,26.0,3.0,N,N,N,N,chunk172.csv
1373,200073334,2020-01-07 17:24:31,CARDBR,2,CARDBR,2,01/07/2020 05:24:35 PM,Y,4,01/07/2020 05:25:02 PM,...,77.0,41.0,308.0,17.0,9.0,N,N,N,N,chunk165.csv

In [12]:
ems2020_excerpt_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13117 entries, 0 to 13116
Data columns (total 32 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   CAD_INCIDENT_ID                 13117 non-null  int64
 1   INCIDENT_DATETIME               13117 non-null  object
 2   INITIAL_CALL_TYPE               13117 non-null  object
 3   INITIAL_SEVERITY_LEVEL_CODE     13117 non-null  int64
 4   FINAL_CALL_TYPE                 13117 non-null  object
 5   FINAL_SEVERITY_LEVEL_CODE       13117 non-null  int64
 6   FIRST_ASSIGNMENT_DATETIME       13010 non-null  object
 7   VALID_DISPATCH_RSPNS_TIME_INDC  13117 non-null  object
 8   DISPATCH_RESPONSE_SECONDS_QY    13117 non-null  int64
 9   FIRST_ACTIVATION_DATETIME       12988 non-null  object
 10  FIRST_ON_SCENE_DATETIME         12533 non-null  object
 11  VALID_INCIDENT_RSPNS_TIME_INDC  13117 non-null  object
 12  INCIDENT_RESPONSE_SECONDS_QY    12533 non-null  float64
 13  INCIDENT_TRAVEL_TM_SECONDS_QY   12533 non-null  float64
 14  FIRST_TO_HOSP_DATETIME          7870 non-null   object
 15  FIRST_HOSP_ARRIVAL_DATETIME     7791 non-null   object
 16  INCIDENT_CLOSE_DATETIME         13110 non-null  object
 17  HELD_INDICATOR                  13117 non-null  object
 18  INCIDENT_DISPOSITION_CODE       12985 non-null  float64
 19  BOROUGH                         13117 non-null  object
 20  INCIDENT_DISPATCH_AREA          13117 non-null  object
 21  ZIPCODE                         12987 non-null  float64
 22  POLICEPRECINCT                  12988 non-null  float64
 23  CITYCOUNCILDISTRICT             12988 non-null  float64
 24  COMMUNITYDISTRICT               12988 non-null  float64
 25  COMMUNITYSCHOOLDISTRICT         12978 non-null  float64
 26  CONGRESSIONALDISTRICT           12988 non-null  float64
 27  REOPEN_INDICATOR                13117 non-null  object
 28  SPECIAL_EVENT_INDICATOR         13117 non-null  object
 29  STANDBY_INDICATOR               13117 non-null  object
 30  TRANSFER_INDICATOR              13117 non-null  object
 31  source                          13117 non-null  object
dtypes: float64(9), int64(4), object(19)
memory usage: 3.2+ MB

In [14]:
## datatypes include floats, integers, and objects
##32 columns, 13117 rows

In [16]:
ems2020_excerpt_df.head (7)

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,...,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR,source
0,201101264,2020-04-19 10:25:47,INJMIN,7,INJMIN,7,04/19/2020 10:26:24 AM,Y,37,04/19/2020 10:26:24 AM,...,40.0,8.0,201.0,7.0,15.0,N,N,N,N,chunk170.csv
1,200423766,2020-02-11 19:25:47,CARD,3,SICK,6,02/11/2020 07:25:56 PM,Y,9,02/11/2020 07:26:09 PM,...,52.0,14.0,207.0,10.0,15.0,N,N,N,N,chunk166.csv
2,200434110,2020-02-12 21:36:52,UNC,2,UNC,2,02/12/2020 09:37:24 PM,Y,32,02/12/2020 09:38:27 PM,...,106.0,32.0,410.0,27.0,8.0,N,N,N,N,chunk166.csv
3,201610121,2020-06-09 00:52:30,DRUG,4,DRUG,4,06/09/2020 12:52:44 AM,Y,14,06/09/2020 12:52:59 AM,...,19.0,4.0,108.0,2.0,12.0,N,N,N,N,chunk171.csv
4,200034112,2020-01-03 20:44:05,DRUG,4,DRUG,4,01/03/2020 08:44:11 PM,Y,6,01/03/2020 08:44:17 PM,...,66.0,39.0,312.0,15.0,7.0,N,N,N,N,chunk165.csv
5,200530247,2020-02-22 01:26:18,DRUG,4,DRUG,4,02/22/2020 01:27:21 AM,Y,63,02/22/2020 01:27:41 AM,...,25.0,8.0,111.0,4.0,12.0,N,N,N,N,chunk167.csv
6,200543279,2020-02-23 19:08:27,UNC,2,UNC,2,02/23/2020 07:08:44 PM,Y,17,02/23/2020 07:09:16 PM,...,44.0,8.0,204.0,9.0,15.0,N,N,N,N,chunk167.csv

In [18]:
ems2020_excerpt_df.sample (10)

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,...,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR,source
274,201111592,2020-04-20 11:34:54,PEDSTR,3,PEDSTR,3,04/20/2020 11:35:39 AM,Y,45,04/20/2020 11:35:56 AM,...,106.0,32.0,410.0,27.0,5.0,N,N,N,N,chunk170.csv
12520,200943509,2020-04-03 14:16:04,UNC,2,UNC,2,04/03/2020 02:16:20 PM,Y,16,04/03/2020 02:16:26 PM,...,120.0,49.0,501.0,31.0,11.0,N,N,N,N,chunk169.csv
7149,201672057,2020-06-15 14:56:30,DRUG,4,DRUG,4,06/15/2020 02:56:55 PM,Y,25,06/15/2020 02:57:08 PM,...,43.0,18.0,209.0,12.0,15.0,N,N,N,N,chunk171.csv
6839,200831633,2020-03-23 09:59:18,UNC,2,SICK,6,03/23/2020 10:00:18 AM,Y,60,03/23/2020 10:00:36 AM,...,114.0,22.0,401.0,30.0,12.0,N,N,N,N,chunk168.csv
6928,200110669,2020-01-11 04:06:17,ABDPN,5,ABDPN,5,01/11/2020 04:06:32 AM,Y,15,01/11/2020 04:06:51 AM,...,42.0,17.0,203.0,9.0,15.0,N,N,N,N,chunk165.csv
6005,200702625,2020-03-10 14:41:19,EDP,7,EDP,7,03/10/2020 02:41:29 PM,Y,10,03/10/2020 02:41:49 PM,...,7.0,2.0,103.0,1.0,12.0,N,N,N,N,chunk168.csv
3919,200412379,2020-02-10 13:35:59,UNKNOW,4,CVAC,2,02/10/2020 01:46:10 PM,Y,611,02/10/2020 01:47:26 PM,...,25.0,8.0,111.0,4.0,13.0,N,N,N,N,chunk166.csv
9140,200952912,2020-04-04 13:16:58,ABDPFC,5,ABDPFC,5,04/04/2020 01:17:40 PM,Y,42,04/04/2020 01:22:41 PM,...,44.0,16.0,204.0,9.0,15.0,N,N,N,N,chunk169.csv
1631,200611583,2020-03-01 10:38:10,CVAC,2,UNC,2,03/01/2020 10:38:47 AM,Y,37,03/01/2020 10:39:00 AM,...,32.0,9.0,110.0,5.0,13.0,N,N,N,N,chunk167.csv
10989,201792693,2020-06-27 17:10:09,INJURY,4,INJURY,4,06/27/2020 05:10:31 PM,Y,22,06/27/2020 05:10:43 PM,...,108.0,26.0,402.0,24.0,14.0,N,N,N,N,chunk172.csv

In [20]:
ems2020_excerpt_df.tail (6)

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,...,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR,source
13111,200870168,2020-03-27 00:42:59,INJURY,5,INJURY,5,03/27/2020 12:43:13 AM,Y,14,03/27/2020 12:43:28 AM,...,109.0,19.0,407.0,25.0,3.0,N,N,N,N,chunk168.csv
13112,200393407,2020-02-08 19:49:33,DIFFBR,2,DIFFBR,2,02/08/2020 07:52:34 PM,Y,181,02/08/2020 07:53:00 PM,...,72.0,38.0,307.0,15.0,7.0,N,N,N,N,chunk166.csv
13113,200034618,2020-01-03 22:51:33,INJURY,5,INJURY,5,01/03/2020 10:51:39 PM,Y,6,01/03/2020 10:52:21 PM,...,75.0,42.0,305.0,19.0,8.0,N,N,N,N,chunk165.csv
13114,200424355,2020-02-11 21:51:09,SICK,6,SICK,6,02/11/2020 09:52:09 PM,Y,60,02/11/2020 09:52:18 PM,...,48.0,15.0,206.0,10.0,15.0,N,N,N,N,chunk166.csv
13115,201742708,2020-06-22 15:57:44,MVAINJ,4,MVAINJ,4,06/22/2020 03:58:07 PM,Y,23,06/22/2020 03:58:19 PM,...,62.0,47.0,311.0,21.0,11.0,N,N,N,N,chunk172.csv
13116,200865674,2020-03-26 19:33:19,DIFFFC,2,DIFFFC,2,03/26/2020 07:33:50 PM,Y,31,03/26/2020 07:34:08 PM,...,103.0,27.0,412.0,29.0,5.0,N,N,N,N,chunk168.csv

In [42]:
whathappened = ems2020_excerpt_df["FINAL_CALL_TYPE"].iat[2245]

In [44]:
whathappened

'UNC'

In [68]:
##targeting an excel sheet
cbp_df = pd.read_excel("multi-data.xlsx", sheet_name = 2, skiprows =6)

In [70]:
cbp_df.head (15)

,date_in,date_out,hours_in_custody,age_group,gender,citizenship,border,sector,field_office
0,2017-01-20 00:10:00,2017-01-20 10:08:00,9.950000,6-8 years,Female,EL SALVADOR,SBO,(b)(7)(E ),NaN
1,2017-01-20 00:15:00,2017-01-24 17:30:00,113.233333,3-5 years,Female,GUATEMALA,SBO,(b)(7)(E ),NaN
2,2017-01-20 00:22:00,2017-01-24 17:47:00,113.416667,3-5 years,Female,BRAZIL,SBO,(b)(7)(E ),NaN
3,2017-01-20 00:30:00,2017-01-21 06:35:00,30.083333,12-14 years,Male,EL SALVADOR,SBO,(b)(7)(E ),NaN
4,2017-01-20 00:30:00,2017-01-21 13:03:00,36.533333,3-5 years,Male,HONDURAS,SBO,(b)(7)(E ),NaN
5,2017-01-20 00:30:00,2017-01-21 15:30:00,38.983333,Under 1 year,Male,HONDURAS,SBO,(b)(7)(E ),NaN
6,2017-01-20 00:35:00,2017-01-21 11:52:00,35.266667,6-8 years,Male,GUATEMALA,SBO,(b)(7)(E ),NaN
7,2017-01-20 00:35:00,2017-01-20 15:14:00,14.633333,6-8 years,Male,GUATEMALA,SBO,(b)(7)(E ),NaN
8,2017-01-20 00:35:00,2017-01-21 11:52:00,35.266667,3-5 years,Male,GUATEMALA,SBO,(b)(7)(E ),NaN
9,2017-01-20 00:35:00,2017-01-21 11:52:00,35.266667,9-11 years,Male,GUATEMALA,SBO,(b)(7)(E ),NaN
10,2017-01-20 00:45:00,2017-01-20 13:15:00,12.500000,15-18 years,Male,EL SALVADOR,SBO,(b)(7)(E ),NaN
11,2017-01-20 01:19:00,2017-01-21 02:30:00,25.166667,15-18 years,Male,INDIA,SBO,(b)(7)(E ),NaN
12,2017-01-20 01:19:00,2017-01-21 02:30:00,25.166667,15-18 years,Male,INDIA,SBO,(b)(7)(E ),NaN
13,2017-01-20 01:20:00,2017-01-24 17:30:00,112.166667,6-8 years,Male,HONDURAS,SBO,(b)(7)(E ),NaN
14,2017-01-20 01:20:00,2017-01-20 13:40:00,12.333333,9-11 years,Female,EL SALVADOR,SBO,(b)(7)(E ),NaN

In [73]:
cbp_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 95721 entries, 0 to 95720
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   date_in           95721 non-null  datetime64[ns]
 1   date_out          95223 non-null  datetime64[ns]
 2   hours_in_custody  95506 non-null  float64
 3   age_group         95716 non-null  object
 4   gender            95721 non-null  object
 5   citizenship       95721 non-null  object
 6   border            95721 non-null  object
 7   sector            95721 non-null  object
 8   field_office      0 non-null      float64
dtypes: datetime64[ns](2), float64(2), object(5)
memory usage: 6.6+ MB

In [75]:
## datatypes include objects, floats, datetimes
## there are 9 columns and 95_720 rows of data (not counting skiprows)

In [77]:
cbp_df.tail(3)

,date_in,date_out,hours_in_custody,age_group,gender,citizenship,border,sector,field_office
95718,2018-06-02 13:05:00,2018-06-05 23:35:00,82.483333,6-8 years,Female,GUATEMALA,SBO,(b)(7)(E ),NaN
95719,2018-06-02 13:05:00,2018-06-04 00:54:00,35.800000,15-18 years,Male,GUATEMALA,SBO,(b)(7)(E ),NaN
95720,2018-06-02 13:20:00,2018-06-06 07:27:00,90.100000,6-8 years,Male,GUATEMALA,SBO,(b)(7)(E ),NaN

In [81]:
cbp_df.sample(20)

,date_in,date_out,hours_in_custody,age_group,gender,citizenship,border,sector,field_office
42401,2017-11-23 16:10:00,2017-11-24 01:07:00,8.933333,15-18 years,Male,MEXICO,SBO,(b)(7)(E ),NaN
88833,2018-05-15 22:15:00,2018-05-17 10:44:00,36.466667,15-18 years,Male,HONDURAS,SBO,(b)(7)(E ),NaN
47454,2017-12-11 17:20:00,2017-12-13 06:00:00,36.650000,15-18 years,Male,GUATEMALA,SBO,(b)(7)(E ),NaN
3930,2017-02-02 19:28:00,2017-02-03 15:03:00,19.566667,6-8 years,Male,HONDURAS,SBO,(b)(7)(E ),NaN
15102,2017-06-23 08:30:00,2017-06-24 05:41:00,21.166667,15-18 years,Male,EL SALVADOR,SBO,(b)(7)(E ),NaN
56789,2018-01-20 22:00:00,2018-01-21 13:10:00,15.150000,12-14 years,Female,HONDURAS,SBO,(b)(7)(E ),NaN
74500,2018-04-02 19:05:00,2018-04-09 09:05:00,157.983333,9-11 years,Female,GUATEMALA,SBO,(b)(7)(E ),NaN
66488,2018-03-05 18:20:00,2018-03-09 10:56:00,88.583333,3-5 years,Female,GUATEMALA,SBO,(b)(7)(E ),NaN
71939,2018-03-25 14:00:00,2018-03-28 22:18:00,80.283333,9-11 years,Male,GUATEMALA,SBO,(b)(7)(E ),NaN
74678,2018-04-03 14:00:00,2018-04-06 12:32:00,70.516667,9-11 years,Male,GUATEMALA,SBO,(b)(7)(E ),NaN
3127,2017-01-30 07:27:00,2017-01-31 11:00:00,27.533333,15-18 years,Female,HONDURAS,SBO,(b)(7)(E ),NaN
61501,2018-02-11 15:00:00,2018-02-13 14:30:00,47.483333,Under 1 year,Female,GUATEMALA,SBO,(b)(7)(E ),NaN
85208,2018-05-05 14:40:00,2018-05-06 22:34:00,31.883333,15-18 years,Male,INDIA,SBO,(b)(7)(E ),NaN
58639,2018-01-28 16:05:00,2018-01-29 21:11:00,29.083333,15-18 years,Female,HONDURAS,SBO,(b)(7)(E ),NaN
63834,2018-02-22 02:00:00,2018-02-24 15:33:00,61.533333,15-18 years,Male,GUATEMALA,SBO,(b)(7)(E ),NaN
32265,2017-10-08 03:00:00,2017-10-08 12:23:00,9.366667,15-18 years,Male,MEXICO,SBO,(b)(7)(E ),NaN
8337,2017-03-20 13:20:00,2017-03-21 15:38:00,26.283333,15-18 years,Male,MEXICO,SBO,(b)(7)(E ),NaN
86993,2018-05-10 15:40:00,2018-05-13 19:32:00,75.850000,12-14 years,Male,EL SALVADOR,SBO,(b)(7)(E ),NaN
36697,2017-10-31 06:30:00,2017-11-03 14:52:00,80.350000,15-18 years,Female,GUATEMALA,SBO,(b)(7)(E ),NaN
49266,2017-12-16 21:50:00,2017-12-18 01:41:00,27.833333,12-14 years,Male,GUATEMALA,SBO,(b)(7)(E ),NaN

In [83]:
eighthcustody = cbp_df["hours_in_custody"].iat[7]

In [85]:
eighthcustody

14.6333333333333